fix(query-params): Fix array query params documentation (#389)
This commit adds a Github Action workflow to check whether the array query params in the OpenAPI end with `[]` as expected by the API. It also fixes the invalid query params in the documentation.

Below is the output of the Github Action before the fix:

```shell
> Run ./scripts/check_array_params.rb src/resources

ERROR: Found 10 array parameter(s) without [] suffix:

  GET /activity_logs
    File: src/resources/activity_logs.yml
    Parameter: activity_types
    Fix: Rename to 'activity_types[]'

  GET /activity_logs
    File: src/resources/activity_logs.yml
    Parameter: activity_sources
    Fix: Rename to 'activity_sources[]'

  GET /activity_logs
    File: src/resources/activity_logs.yml
    Parameter: user_emails
    Fix: Rename to 'user_emails[]'

  GET /activity_logs
    File: src/resources/activity_logs.yml
    Parameter: resource_ids
    Fix: Rename to 'resource_ids[]'

  GET /activity_logs
    File: src/resources/activity_logs.yml
    Parameter: resource_types
    Fix: Rename to 'resource_types[]'

  GET /api_logs
    File: src/resources/api_logs.yml
    Parameter: http_methods
    Fix: Rename to 'http_methods[]'

  GET /api_logs
    File: src/resources/api_logs.yml
    Parameter: http_statuses
    Fix: Rename to 'http_statuses[]'

  GET /api_logs
    File: src/resources/api_logs.yml
    Parameter: api_version
    Fix: Rename to 'api_version[]'

  GET /credit_notes
    File: src/resources/credit_notes.yaml
    Parameter: billing_entity_codes
    Fix: Rename to 'billing_entity_codes[]'

  GET /invoices
    File: src/resources/invoices.yaml
    Parameter: billing_entity_codes
    Fix: Rename to 'billing_entity_codes[]'
Error: Process completed with exit code 1.
```